---
- name: Creation of a Terraria tModLoader
  hosts: terraria
  become: yes
  vars:
    terraria_user: "terraria"
    server_dir: "/home/{{ terraria_user }}/server"
    config_dir: "/home/{{ terraria_user }}/.local/share/Terraria/tModLoader"
    tmodloader_version: "v2026.01.3.3"

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: 
          - wget
          - unzip
          - screen
          - dotnet-sdk-8.0
        state: present
        update_cache: yes

    - name: Create "terraria" user with home folder
      ansible.builtin.user:
        name: "{{ terraria_user }}"
        shell: /bin/bash
        home: "/home/{{ terraria_user }}"

    - name: Create required server folders
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ terraria_user }}"
        group: "{{ terraria_user }}"
        mode: '0755'
      with_items:
        - "{{ server_dir }}"
        - "{{ config_dir }}/Mods"
        - "{{ config_dir }}/Worlds"

    - name: Get server binaries
      ansible.builtin.get_url:
        url: "https://github.com/tModLoader/tModLoader/releases/download/{{ tmodloader_version }}/tModLoader.zip"
        dest: "{{ server_dir }}/tModLoader.zip"
        owner: "{{ terraria_user }}"
        group: "{{ terraria_user }}"
        mode: '0755'

    - name: Unarchive the binaries
      ansible.builtin.unarchive:
        remote_src: true
        src: "{{ server_dir }}/tModLoader.zip"
        dest: "{{ server_dir }}"
        owner: "{{ terraria_user }}"
        group: "{{ terraria_user }}"
        mode: '0755'

    - name: Paste server configuration
      ansible.builtin.copy:
        src: serverconfig.txt
        dest: "{{ server_dir }}/serverconfig.txt"
        owner: "{{ terraria_user }}"
        group: "{{ terraria_user }}"
        mode: '0755'

    - name: Create systemd service file
      ansible.builtin.copy:
        dest: /etc/systemd/system/terraria.service
        content: |
          [Unit]
          Description=Terraria tModLoader Server
          After=network.target

          [Service]
          User={{ terraria_user }}
          WorkingDirectory={{ server_dir }}
          ExecStart=/usr/bin/screen -DmS terraria {{ server_dir }}/start-tModLoaderServer.sh -nosteam -config {{ server_dir }}/serverconfig.txt
          ExecStop=/usr/bin/screen -p 0 -S terraria -X stuff "exit$(printf \\r)"
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target

    - name: Reload of systemd and keep the system stopped for mod install
      systemd:
        name: terraria
        daemon_reload: yes
        enabled: yes
        # On ne le "start" pas encore car les fichiers .tmod ne sont pas là
        state: stopped 

    - name: Check if "mods" folder exists locally
      ansible.builtin.stat:
        path: "./mods"
      register: folder_check
      delegate_to: localhost
      run_once: true

    - name: Start service if no mods are found locally
      ansible.builtin.set_fact:
        trigger_service: true
      when: not folder_check.stat.exists
      changed_when: true
      notify: "Start terraria service"

    - name: Import mods on the server if they exists
      ansible.builtin.copy:
        src: ./mods/
        dest: "{{ config_dir }}/Mods"
        owner: "{{ terraria_user }}"
        group: "{{ terraria_user }}"
        mode: '0755'
      when: folder_check.stat.exists

  handlers:
    - name: Start terraria service
      ansible.builtin.service:
        name: terraria.service
        state: started
